### ISSUE TITLE
encoding to svg

### ISSUE THREAD

**Issue by aminvandh** [GameMaker2k/PyUPC-EAN#12]
Hi, How can i convert a code to svg ?
`create_upce_barcode(upc,outfile="./upce.svg",......, mageoutlib="cairosvg") `this generates a png again

**Comment by KazukiPrzyborowski** [comment]
I've been trying to get this to work but I could not figure out what is wrong with the code as no mater what I've change it still outputs png or a png inside a svg file so for now this feature doesn't work yet.

**Comment by KazukiPrzyborowski** [comment]
Just fixed this it should work now. ^_^
